name: netlify-application-workflow
on: 
  push:
    branches:
      - 'master'
  workflow_dispatch:
jobs:
  netlify-application-job-lint:
    runs-on: macos-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v5
      - name: Install node
        uses: actions/setup-node@v4
        with: 
          node-version: 23
      - name: Install the dependencies
        run: npm ci
      - name: Create Lint for the Javascript in the project
        run: echo "Linting completed successfully."
  netlify-application-job-test:
    needs: netlify-application-job-lint
    runs-on: macos-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v5
      - name: Install Node
        uses: actions/setup-node@v4
        with: 
          node-version: 23
      - name: Install the dependencies
        run: npm ci
      - name: Test the code
        run: npm run test
  netlify-application-job-deploy:
    needs: netlify-application-job-test
    runs-on: macos-latest
    steps:
      - name: Get code
        uses: actions/checkout@v5
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 23
      - name: Install the dependencies
        run: npm ci
      - name: Build the code
        run: npm run build
      - name: Deploy the application
        run: echo "Deploying the application to the server."
   
     
